name: Automatizador BOJA

on:
  schedule:
    # De lunes (1) a viernes (5), cada 15 minutos entre las 08:00 y las 15:00 UTC
    - cron: '0,15,30,45 6-13 * * 1-5'
  workflow_dispatch: # Permite lanzarlo manualmente desde GitHub cuando quieras probarlo

jobs:
  verificar-boja:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install @supabase/supabase-js

      - name: Ejecutar script de verificación
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: node capturador.js
