name: Automatizador BOJA[cite: 3]

on:
  schedule:
    - cron: '0,15,30,45 6-13 * * 1-5'

  workflow_dispatch:

jobs:
  verificar-boja:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio[cite: 3]
        uses: actions/checkout@v4[cite: 3]

      - name: Configurar Node.js[cite: 3]
        uses: actions/setup-node@v4[cite: 3]
        with:
          node-version: '20'[cite: 3]

      - name: Instalar dependencias[cite: 3]
        run: npm install

      - name: Ejecutar script de verificación[cite: 3]
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

        run: node capturador.js[cite: 3]
